apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-to-end
  labels:
    app: end-to-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: end-to-end
  template:
    metadata:
      labels:
        app: end-to-end
    spec:
      containers:
      - name: end-end
        image: hasanabdirahman/end-end:v1 
        ports:
        - containerPort: 80
    
      imagePullSecrets:
        - name: myregistrykey
