apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: pYUldiRFJtT1ROYVVWUk9Sdz09IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogIlNHRnpZVzVCWW1ScGNtRm9iV0Z1T21kb2RWOTNkamQ0TnpCM2RrVlpWa2RPY2xSSVNHZHBabk56YldWMFZtdzBaamt6V2xGVVRrYz0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJhR0Z6WVc1aFltUnBjbUZvYldGdU9tUmphM0pmY0dGMFgwOUNUMlpCVG5kVFlVaHhXVTFmUzNBNU1tTm9lbTVyUzE5dVZRPT0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiWC1NZXRhLVNvdXJjZS1DbGllbnQiOiAiZ2l0aHViL2NvZGVzcGFjZXMiCgl9Cn0=